### PR TITLE
Logarithmic scale

### PR DESCRIPTION
**Pull request by danielkucera**

### CODE REVIEW

**Comment by danielkucera** [comment]
So I have managed to make the button work (with zero knowledge of react!).
Please review.
Thank you.

**Comment by aadnekar** [comment]
Thank you @danielkucera, this looks promising.
We would like to test this as soon as we get time to do so :+1:

**Comment by danielkucera** [comment]
Hi @aadnekar , is there something I can do to get this merged?

**Comment by aadnekar** [comment]
> Hi @aadnekar , is there something I can do to get this merged?

Hello @danielkucera, yes, I believe we can work something out! And thanks again for reaching out.
First, I'm sorry it has taken so long.

I must admit that I'm not a domain expert, so it would be good to figure out the scope of this feature. Could you, if you have time, write down some expectations for when to use, and also when not to use the Logarithmic Scale. Images / gifs are very welcome in order for us to compare when testing it locally.

I remember when I did a quick spin of it in January, that I had some big gaps in my graph, but I assume that is because the chart cuts the graph when the values are lower then `1 uA`. Is this, in your opinion, expected?

So, in order to get this merged, I would as a minimum want:

1. A description of the feature
2. An image of the feature working
3. (If present) Image and description of scenarios where the feature does not work as expected.

I've added the (3) so that we may discuss possible solutions together.

We'll start a new sprint next Tuesday, and I'll see if I can add this feature in the upcoming sprint. 

Does that sound fine?

Thanks again for your contribution and patience

**Comment by danielkucera** [comment]
Sure, I'll try my best.

1. This MR allows you to choose logarithmic scale for the Y-axis showing current. This might be useful when the current has a wide dynamic range (from uAs to hundreds of mA) a you, on one hand want to see the top peaks of the current, and also bottom values in uA. Using this scale you can read if it is 3uA or 30uA and 5 or 50mA - it is harder to read exact value from the graph but you can always hover over with mouse.
2. Here is an image comparing the same "signal" in both scales.
On the first picture you can quite precisely read values between 10 and 100mA but you have no idea about the values below 5mA - they might be ones, tens, hundreds of uAmps - one cannot tell.
FknLNLKXEAAKnFX
On the second picture you can read the scale of the signal, the range it belongs to and roughly the value.
FknLNLNXkAAxggg
3. in the second picture you can also see where it is problematic - it cannot display 0uA from it's principle. One can overcome this by locking y-axis to minimum of 0.1uA but I didn't consider this as a big problem. Maybe if the device was reporting maximum of it's smallest resolution (e.g. 0.1uA) instead of zero it would be more precise because it cannot accurately say if the current is total 0 or just something below 0.1uA.

**Comment by wlgrd** [comment]
I notice that at around 3m11s there's a gap in the data shown in the second picture (with the logarithmic scale). This looks to be the same plot twice in different scales, so I don't see a reason for data to be missing. Any insight?

**Comment by danielkucera** [comment]
This is the point 3. - it cannot display zero, I suppose.

**Comment by wlgrd** [comment]
> This is the point 3. - it cannot display zero, I suppose.

That makes sense. Maybe the software can cap the negative incoming values to e.g 1e-20 instead of 0?

**Comment by aadnekar** [comment]
> 

This will require us to switch between capped values and not-capped values when you change the scale. We could experiment a bit with it, but I'm a little concerned that we'll need to run through all the samples to check if there are capped/not-capped values that needs to be converted?

As a starting point we can try it only for the Logarithmic Scale, and only do it on the samples that will be included in the rendered graph.

The data used by the chart can be found here: https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/blob/055a494810b547be44a8fb8074853023c9ab6802/src/components/Chart/AmpereChart.jsx#L120

I would probably investigated if you could add a dependency to what scale you are using in this `useEffect` https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/blob/055a494810b547be44a8fb8074853023c9ab6802/src/components/Chart/Chart.jsx#L299-L323, and then pass the scale into the data processor, and if the scale is logarithmic then you'd cap the values to what @wlgrd mentioned above.

@danielkucera, will you let me know what you think, and if you want any resources?

Thanks again, and let me know if you want to look at it more closely!

**Comment by danielkucera** [comment]
@aadnekar , I think this is too big change for me to write. 
Can't we leave it as is and if someone don't understand the output he can always switch back to linear scale?

**Comment by danielkucera** [comment]
I have measured the device again and the result is different:

Screenshot from 2023-03-05 18-40-04
Screenshot from 2023-03-05 18-40-09

It doesn't show holes for zero but some aA or fA (femto, ato?).
 Is it possible that the device reports NaN for some timestamps? 
I've noticed these are being handled in here:
https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/blob/055a494810b547be44a8fb8074853023c9ab6802/src/components/Chart/data/dataSelector.ts#L49
In that case, the holes in the first example would be correct.

**Comment by danielkucera** [comment]
What is interesting, that these values are really there even for linear scale but really hard to read/notice:
Screenshot from 2023-03-05 18-51-03
Screenshot from 2023-03-05 18-51-19
Does this mean that the device is measuring yA (whatever "y" means)?

**Comment by aadnekar** [comment]
Hello, we did some investigating, and found some issues that we are not comfortable releasing.
In the two images below, we see that a big portion of the graph is not visible when using the Logarithmic Scale.

image

image

The plot is there when you zoom in, but is not rendered when you are zoomed out. We, unfortunately, do not have the resources to investigate more at the moment. However, we do appreciate the feature, and we have put it in our backlog, but we do not know when we will be able to prioritize looking into it.

Thank you again @danielkucera. 
Please, do not hesitate to reach out again.

**Comment by danielkucera** [comment]
@aadnekar , can you please share .ppk file with the data you posted?

**Comment by danielkucera** [comment]
@aadnekar , I believe I have found an acceptable solution.

For linear scale everything stays the same. For log scale, zero values are replaced by NaN which are better handled in chart.js. Please check and test the latest version. It works with the dataset you provided:

**Review by aadnekar — APPROVED** [review]
Looks really nice! I've added a changelog entry, and given you credit for the feature. Thank you for contributing! :fireworks: 

Please, go a head and merge when you are ready :smile:

**Comment by aadnekar** [comment]
We are trying to setup the pipeline to run on your source.

**Comment by aadnekar** [comment]
@danielkucera , we had to change some settings on Azure Pipelines, but it does not look like it triggers on old PRs. I will try to close and reopen the PR to see if it triggers.

**Comment by aadnekar** [comment]
As it did not trigger on Reopen, I will merge it without the status check.

**Comment by danielkucera** [comment]
Shall I try to open a new PR to run the pipeline?

**Comment by aadnekar** [comment]
> Shall I try to open a new PR to run the pipeline?

No, it's fine. I just bypassed the checks this time. The pipeline ran after it was merged, and it was all green.
Thanks again @danielkucera, hope you don't mind that I just merged it.

**Comment by danielkucera** [comment]
Hi @aadnekar , when will this be part of a standard release? It is not in 3.5.5.

**Pull request merged**
